### ISSUE TITLE
EPIC: Roll With It!

### ISSUE THREAD

**Issue by Icyvexen** [Icyvexen/rpgscripts#2]
Implement the following:
- [x] Ship Names (#5)
- [x] Books (#6)
- [ ] Potions
  - [ ] Have MagicItems call this table when completed
- [ ] Wands
  - [ ] Have MagicItems call this table when completed
- [ ] Determine what other tables from [Rusted Iron Games](https://rustedirongames.com/) to use
